"""Tests for `livespec_dev_tooling/fleet/_member_sources.py`.

Each case builds a real directory tree under `tmp_path` and reads it, because
what is under test IS the walk-and-classify: a fake filesystem would only
restate the classification the test is meant to check.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from returns.io import IOFailure, IOSuccess
from returns.unsafe import unsafe_perform_io

from livespec_dev_tooling.config import Config, load_config
from livespec_dev_tooling.fleet._member_sources import (
    MemberSourcesUnreadable,
    read_member_sources,
)

if TYPE_CHECKING:
    from livespec_dev_tooling.fleet._public_api_graph import MemberSources

__all__: list[str] = []


def write(*, root: Path, rel: str, text: str) -> Path:
    """Write `text` at `rel` under `root`, creating parents."""
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    _ = path.write_text(text, encoding="utf-8")
    return path


def read_ok(*, root: Path, config: Config | None = None) -> MemberSources:
    """The `MemberSources` of a successful read."""
    result = read_member_sources(root=root, config=Config() if config is None else config)
    assert isinstance(result, IOSuccess)
    return unsafe_perform_io(result.unwrap())


def read_failure(*, root: Path) -> MemberSourcesUnreadable:
    """The `MemberSourcesUnreadable` of a failed read."""
    result = read_member_sources(root=root, config=Config())
    assert isinstance(result, IOFailure)
    return unsafe_perform_io(result.failure())


def test_the_defining_universe_excludes_tests_and_the_consuming_one_includes_them(
    *, tmp_path: Path
) -> None:
    """The asymmetry IS v178's shape: form 1 defines, form 2 also consumes."""
    _ = write(root=tmp_path, rel="pkg/mod.py", text="def compute() -> int:\n    return 1\n")
    _ = write(root=tmp_path, rel="tests/test_mod.py", text="from pkg.mod import compute\n")
    _ = write(root=tmp_path, rel="tests/conftest.py", text="VALUE = 1\n")
    sources = read_ok(root=tmp_path)
    assert set(sources.defining) == {Path("pkg/mod.py")}
    assert set(sources.consuming) == {
        Path("pkg/mod.py"),
        Path("tests/test_mod.py"),
        Path("tests/conftest.py"),
    }
    assert sources.defining[Path("pkg/mod.py")] == "def compute() -> int:\n    return 1\n"


def test_a_conftest_outside_the_test_tree_still_counts_as_a_consumer(*, tmp_path: Path) -> None:
    """`filter_first_party_py` drops `conftest.py` BY NAME, wherever it sits."""
    _ = write(root=tmp_path, rel="pkg/conftest.py", text="from other.mod import helper\n")
    sources = read_ok(root=tmp_path)
    assert set(sources.defining) == set()
    assert set(sources.consuming) == {Path("pkg/conftest.py")}


def test_a_declared_test_tree_prefix_is_honored_rather_than_the_default(*, tmp_path: Path) -> None:
    _ = write(
        root=tmp_path,
        rel="pyproject.toml",
        text='[tool.livespec_dev_tooling]\ntests_tree_prefix = "spec/"\n',
    )
    _ = write(root=tmp_path, rel="spec/test_mod.py", text="VALUE = 1\n")
    _ = write(root=tmp_path, rel="tests/test_mod.py", text="VALUE = 2\n")
    sources = read_ok(root=tmp_path, config=load_config(repo_root=tmp_path))
    # `tests/` is no longer the test tree, so it is PRODUCT here; `spec/` is
    # the declared one and is excluded from the defining universe.
    assert set(sources.defining) == {Path("tests/test_mod.py")}
    assert set(sources.consuming) == {Path("spec/test_mod.py"), Path("tests/test_mod.py")}


def test_vendored_and_template_and_generated_sources_are_outside_both_universes(
    *, tmp_path: Path
) -> None:
    """Every exclusion comes from `filter_first_party_py`, not a second list."""
    _ = write(root=tmp_path, rel="_vendor/returns/io.py", text="VALUE = 1\n")
    _ = write(root=tmp_path, rel="templates/hook.py", text="from pkg.mod import compute\n")
    _ = write(root=tmp_path, rel=".claude/skills/daemon.py", text="VALUE = 1\n")
    _ = write(root=tmp_path, rel="pkg/built.py", text="# @generated by a tool\nVALUE = 1\n")
    _ = write(root=tmp_path, rel="pkg/mod.py", text="def compute() -> int:\n    return 1\n")
    sources = read_ok(root=tmp_path)
    assert set(sources.defining) == {Path("pkg/mod.py")}
    assert set(sources.consuming) == {Path("pkg/mod.py")}


def test_an_unreadable_file_names_itself_rather_than_the_walk_root(*, tmp_path: Path) -> None:
    """A DIRECTORY named `x.py` globs like a file and raises `IsADirectoryError`.

    Chosen over `chmod(0o000)`, which denies nothing to root — and CI runs as
    root inside the sandbox container, so that test would pass locally and
    fail in CI (the livespec-dev-tooling-9sl0 lesson).
    """
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "trap.py").mkdir()
    unreadable = read_failure(root=tmp_path)
    assert unreadable.file == str(tmp_path / "pkg" / "trap.py")
    assert "trap.py" in unreadable.detail


def test_a_file_that_is_not_utf8_names_itself_too(*, tmp_path: Path) -> None:
    """`UnicodeDecodeError` carries the offending BYTES and no filename.

    Reading it off the exception would name the file for an `OSError` and the
    walk ROOT for a decode failure — the weaker diagnostic winning silently,
    against an operator looking at a copy of ANOTHER repo's tree.
    """
    path = tmp_path / "pkg" / "latin.py"
    path.parent.mkdir(parents=True)
    _ = path.write_bytes(b"VALUE = '\xff\xfe not utf-8'\n")
    unreadable = read_failure(root=tmp_path)
    assert unreadable.file == str(path)
    assert "utf-8" in unreadable.detail


def test_a_member_with_no_python_at_all_reads_as_two_empty_universes(*, tmp_path: Path) -> None:
    """The verified fleet case (livespec-console-beads-fabro): zero is legitimate.

    Unlike an empty ARCHIVE — which is a broken read and fails — an empty
    Python universe is a real answer about a real repo, and the difference is
    that the archive of a repo with no `.py` still holds its README.
    """
    _ = write(root=tmp_path, rel="README.md", text="# nothing here\n")
    sources = read_ok(root=tmp_path)
    assert sources.defining == {}
    assert sources.consuming == {}
